import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { Report } from "@/lib/reports";
import { parseStructuredCompanyReport } from "@/lib/structuredReport";

const styles = StyleSheet.create({
  page: { padding: 44, fontSize: 11, fontFamily: "Helvetica", color: "#1a1a1a" },
  title: { fontSize: 20, fontWeight: 700, marginBottom: 4 },
  meta: { fontSize: 10, color: "#666666", marginBottom: 24 },
  sectionTitle: { fontSize: 12, fontWeight: 700, marginTop: 16, marginBottom: 6, color: "#0a5c33" },
  paragraph: { fontSize: 11, lineHeight: 1.5, marginBottom: 6 },
  listItem: { fontSize: 11, lineHeight: 1.5, marginBottom: 4 },
  disclaimer: { fontSize: 9, color: "#888888", marginTop: 28, lineHeight: 1.4 }
});

export function ReportDocument({ report }: { report: Report }) {
  const structured = parseStructuredCompanyReport(report.output);

  return (
    <Document>
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.title}>{report.title}</Text>
        <Text style={styles.meta}>
          {report.module.replace("_", " ").toUpperCase()} · {new Date(report.created_at).toLocaleDateString()}
        </Text>

        {structured ? (
          <>
            <Section title="Executive Summary" text={structured.executiveSummary} />
            <Section title="Investment Thesis" text={structured.investmentThesis} />
            <Section title="Financial Performance" text={structured.financialPerformance} />
            <Section title="Valuation" text={structured.valuation} />
            <Section title="Comparables Analysis" text={structured.comparablesAnalysis} />
            <ListSection title="Strengths" items={structured.strengths} />
            <ListSection title="Risks" items={structured.risks} />
            <Section title="Bull Case" text={structured.bullCase} />
            <Section title="Bear Case" text={structured.bearCase} />
            <ListSection title="Key Questions" items={structured.keyQuestions} />
            <Section title="Limitations & Disclaimer" text={structured.limitations} />
          </>
        ) : (
          <Text style={styles.paragraph}>{report.output}</Text>
        )}

        <Text style={styles.disclaimer}>
          Generated by Melara Capital AI. Educational financial analysis only — not individualized
          investment, tax, legal, accounting, or fiduciary advice.
        </Text>
      </Page>
    </Document>
  );
}

function Section({ title, text }: { title: string; text?: string }) {
  if (!text) return null;
  return (
    <View>
      <Text style={styles.sectionTitle}>{title}</Text>
      <Text style={styles.paragraph}>{text}</Text>
    </View>
  );
}

function ListSection({ title, items }: { title: string; items?: string[] }) {
  if (!items || items.length === 0) return null;
  return (
    <View>
      <Text style={styles.sectionTitle}>{title}</Text>
      {items.map((item, i) => (
        <Text key={i} style={styles.listItem}>
          • {item}
        </Text>
      ))}
    </View>
  );
}
