export type GlossaryCategory =
  | "Valuation & Analysis"
  | "Investing Basics"
  | "Financial Statements"
  | "Retirement"
  | "Taxes";

export type GlossaryTerm = {
  term: string;
  category: GlossaryCategory;
  definition: string;
};

export const GLOSSARY: GlossaryTerm[] = [
  // Valuation & Analysis
  {
    term: "EBITDA",
    category: "Valuation & Analysis",
    definition:
      "Earnings Before Interest, Taxes, Depreciation, and Amortization — a rough proxy for a company's core operating cash profitability, before financing and accounting choices."
  },
  {
    term: "P/E Ratio",
    category: "Valuation & Analysis",
    definition:
      "Price-to-Earnings ratio: share price divided by earnings per share. A quick, imperfect gauge of how expensive a stock is relative to its profits."
  },
  {
    term: "EV / EBITDA",
    category: "Valuation & Analysis",
    definition:
      "Enterprise Value divided by EBITDA. Compares a company's total value (equity plus debt, minus cash) to its operating profit — useful for comparing companies with different debt levels."
  },
  {
    term: "Enterprise Value",
    category: "Valuation & Analysis",
    definition:
      "A company's total value to all capital providers: market cap plus total debt, minus cash. Represents what it would theoretically cost to acquire the whole business."
  },
  {
    term: "Market Capitalization",
    category: "Valuation & Analysis",
    definition: "The total value of a company's outstanding shares: share price multiplied by shares outstanding."
  },
  {
    term: "DCF (Discounted Cash Flow)",
    category: "Valuation & Analysis",
    definition:
      "A valuation method that estimates a company's worth today by projecting its future cash flows and discounting them back to present value using a required rate of return."
  },
  {
    term: "Discount Rate",
    category: "Valuation & Analysis",
    definition:
      "The rate used to convert future cash flows into today's dollars in a DCF — reflecting the time value of money and the riskiness of those cash flows."
  },
  {
    term: "Free Cash Flow",
    category: "Valuation & Analysis",
    definition:
      "Cash generated by operations after subtracting capital expenditures — the cash actually available to pay down debt, pay dividends, buy back stock, or reinvest."
  },
  {
    term: "Comparable Company Analysis",
    category: "Valuation & Analysis",
    definition:
      "Valuing a company by looking at the trading multiples (like EV/EBITDA or P/E) of similar public companies, then applying those multiples to the subject company."
  },
  {
    term: "Terminal Value",
    category: "Valuation & Analysis",
    definition:
      "In a DCF, the estimated value of all cash flows beyond the explicit projection period, capturing the business's long-run worth in a single lump figure."
  },
  {
    term: "ROE (Return on Equity)",
    category: "Valuation & Analysis",
    definition: "Net income divided by shareholders' equity — measures how efficiently a company generates profit from shareholders' invested capital."
  },
  {
    term: "ROA (Return on Assets)",
    category: "Valuation & Analysis",
    definition: "Net income divided by total assets — measures how efficiently a company turns its asset base into profit."
  },
  {
    term: "Beta",
    category: "Valuation & Analysis",
    definition:
      "A measure of a stock's volatility relative to the overall market. A beta above 1 means the stock tends to move more than the market; below 1, less."
  },
  {
    term: "Dividend Yield",
    category: "Valuation & Analysis",
    definition: "Annual dividend per share divided by the current share price, expressed as a percentage."
  },
  {
    term: "Analyst Rating",
    category: "Valuation & Analysis",
    definition:
      "A Wall Street research analyst's Buy/Hold/Sell-style recommendation on a stock, often accompanied by a price target. One opinion among many, not a guarantee."
  },

  // Investing Basics
  {
    term: "Diversification",
    category: "Investing Basics",
    definition:
      "Spreading investments across different assets, sectors, or geographies so that no single investment's poor performance can sink the whole portfolio."
  },
  {
    term: "Index Fund",
    category: "Investing Basics",
    definition:
      "A fund that holds all (or a representative sample) of the securities in a market index, like the S&P 500, aiming to match the index's return rather than beat it."
  },
  {
    term: "ETF (Exchange-Traded Fund)",
    category: "Investing Basics",
    definition:
      "A fund that holds a basket of assets (stocks, bonds, commodities) but trades on an exchange like a single stock, typically with low fees."
  },
  {
    term: "Mutual Fund",
    category: "Investing Basics",
    definition:
      "A pooled investment vehicle, professionally managed, priced once per day after markets close — unlike ETFs, which trade continuously during the day."
  },
  {
    term: "Bull Market",
    category: "Investing Basics",
    definition: "A sustained period of rising prices, typically defined as a 20%+ gain from a recent low."
  },
  {
    term: "Bear Market",
    category: "Investing Basics",
    definition: "A sustained period of falling prices, typically defined as a 20%+ decline from a recent high."
  },
  {
    term: "Volatility",
    category: "Investing Basics",
    definition: "How much and how quickly an asset's price swings up and down over time. Higher volatility means larger, faster price moves in either direction."
  },
  {
    term: "Dollar-Cost Averaging",
    category: "Investing Basics",
    definition:
      "Investing a fixed amount at regular intervals regardless of price, which smooths out the average price paid over time and removes the need to time the market."
  },
  {
    term: "Asset Allocation",
    category: "Investing Basics",
    definition:
      "How a portfolio is divided among asset classes — stocks, bonds, cash, real estate, etc. — usually the biggest driver of a portfolio's risk and return."
  },
  {
    term: "Liquidity",
    category: "Investing Basics",
    definition: "How quickly and easily an asset can be converted to cash without significantly affecting its price."
  },
  {
    term: "Risk Tolerance",
    category: "Investing Basics",
    definition: "An investor's personal capacity and willingness to endure investment losses in pursuit of higher returns."
  },
  {
    term: "Blue-Chip Stock",
    category: "Investing Basics",
    definition: "Shares of a large, well-established, financially sound company with a long track record of reliable performance."
  },
  {
    term: "Market Order vs. Limit Order",
    category: "Investing Basics",
    definition:
      "A market order executes immediately at the current price; a limit order only executes at a specific price or better, trading certainty of execution for price control."
  },
  {
    term: "Expense Ratio",
    category: "Investing Basics",
    definition: "The annual fee a fund charges investors, expressed as a percentage of assets — directly reduces net returns over time."
  },
  {
    term: "Compound Interest",
    category: "Investing Basics",
    definition: "Interest earned on both the original principal and on previously accumulated interest — the engine behind long-term wealth growth."
  },

  // Financial Statements
  {
    term: "Balance Sheet",
    category: "Financial Statements",
    definition:
      "A snapshot of what a company owns (assets), owes (liabilities), and the difference (equity) at a single point in time. Assets = Liabilities + Equity."
  },
  {
    term: "Income Statement",
    category: "Financial Statements",
    definition:
      "Shows revenue, expenses, and profit over a period of time (a quarter or year) — also called the profit & loss statement or P&L."
  },
  {
    term: "Cash Flow Statement",
    category: "Financial Statements",
    definition:
      "Tracks actual cash moving in and out of a business across operating, investing, and financing activities — distinct from accounting profit, which can include non-cash items."
  },
  {
    term: "Revenue",
    category: "Financial Statements",
    definition: "Total money a company brings in from selling goods or services, before any costs are subtracted. Also called sales or the top line."
  },
  {
    term: "Gross Margin",
    category: "Financial Statements",
    definition: "Gross profit (revenue minus cost of goods sold) divided by revenue — shows how much a company keeps after direct production costs."
  },
  {
    term: "Operating Margin",
    category: "Financial Statements",
    definition: "Operating income divided by revenue — profitability after both production costs and operating expenses like R&D and marketing."
  },
  {
    term: "Net Margin",
    category: "Financial Statements",
    definition: "Net income divided by revenue — the percentage of revenue that ultimately becomes bottom-line profit after all expenses, interest, and taxes."
  },
  {
    term: "Working Capital",
    category: "Financial Statements",
    definition: "Current assets minus current liabilities — a measure of a company's short-term liquidity and ability to cover near-term obligations."
  },
  {
    term: "Depreciation & Amortization",
    category: "Financial Statements",
    definition:
      "The gradual expensing of a physical asset's cost (depreciation) or an intangible asset's cost (amortization) over its useful life, rather than all at once."
  },
  {
    term: "Accounts Receivable",
    category: "Financial Statements",
    definition: "Money owed to a company by customers for goods or services already delivered but not yet paid for."
  },
  {
    term: "Accounts Payable",
    category: "Financial Statements",
    definition: "Money a company owes to its suppliers for goods or services already received but not yet paid for."
  },
  {
    term: "Shareholders' Equity",
    category: "Financial Statements",
    definition: "What would be left for shareholders if a company sold all its assets and paid off all its liabilities. Also called book value."
  },
  {
    term: "10-K / 10-Q",
    category: "Financial Statements",
    definition:
      "SEC filings: the 10-K is a public company's detailed annual report; the 10-Q is the shorter quarterly update. Both are primary sources for real financial data."
  },

  // Retirement
  {
    term: "401(k)",
    category: "Retirement",
    definition:
      "An employer-sponsored retirement account allowing pre-tax (traditional) or after-tax (Roth) contributions, often with an employer match, growing tax-advantaged until withdrawal."
  },
  {
    term: "IRA (Individual Retirement Account)",
    category: "Retirement",
    definition: "A personal, tax-advantaged retirement account not tied to an employer, available in traditional (pre-tax) and Roth (after-tax) forms."
  },
  {
    term: "Roth vs. Traditional",
    category: "Retirement",
    definition:
      "Traditional accounts give a tax deduction now and are taxed on withdrawal; Roth accounts are funded with after-tax money but grow and withdraw completely tax-free."
  },
  {
    term: "Employer Match",
    category: "Retirement",
    definition: "Money an employer contributes to your 401(k) based on your own contributions — often described as \"free money\" up to the match limit."
  },
  {
    term: "Required Minimum Distribution (RMD)",
    category: "Retirement",
    definition: "The minimum amount the IRS requires you to withdraw annually from most retirement accounts once you reach a certain age (currently 73)."
  },
  {
    term: "Vesting",
    category: "Retirement",
    definition: "The schedule by which you gain full ownership of employer contributions to your retirement account — leaving before fully vested can forfeit some employer money."
  },
  {
    term: "Safe Withdrawal Rate",
    category: "Retirement",
    definition:
      "The percentage of a retirement portfolio you can withdraw annually with a high likelihood the money lasts through retirement — the classic reference point is 4%, though it's debated."
  },
  {
    term: "Social Security",
    category: "Retirement",
    definition:
      "A U.S. government program providing retirement income based on lifetime earnings history; benefits increase the longer you delay claiming, up to age 70."

  },

  // Taxes
  {
    term: "Capital Gain",
    category: "Taxes",
    definition: "The profit from selling an investment for more than you paid for it. Realized only when you actually sell, not while you hold the position."
  },
  {
    term: "Short-Term vs. Long-Term Capital Gains",
    category: "Taxes",
    definition:
      "Gains on assets held one year or less are taxed as ordinary income; gains on assets held longer than a year qualify for lower long-term capital gains tax rates."
  },
  {
    term: "Cost Basis",
    category: "Taxes",
    definition: "What you originally paid for an investment (plus certain adjustments) — used to calculate taxable gain or loss when you sell."
  },
  {
    term: "Qualified Dividend",
    category: "Taxes",
    definition:
      "A dividend that meets IRS holding-period requirements and is taxed at the lower long-term capital gains rate, instead of as ordinary income."
  },
  {
    term: "Tax-Loss Harvesting",
    category: "Taxes",
    definition:
      "Selling an investment at a loss to offset taxable capital gains elsewhere, potentially reducing your overall tax bill."
  },
  {
    term: "Wash Sale Rule",
    category: "Taxes",
    definition:
      "An IRS rule disallowing a tax loss if you buy the same or a \"substantially identical\" security within 30 days before or after the sale."
  },
  {
    term: "Tax-Advantaged Account",
    category: "Taxes",
    definition:
      "An account like a 401(k), IRA, or HSA that offers a tax break — either up front, on growth, or on withdrawal — compared to a regular taxable brokerage account."
  },
  {
    term: "1099-DIV / 1099-B",
    category: "Taxes",
    definition: "Tax forms brokerages issue reporting dividend income (1099-DIV) and proceeds from investment sales (1099-B) for your tax return."
  }
];

export const GLOSSARY_CATEGORIES: GlossaryCategory[] = [
  "Valuation & Analysis",
  "Investing Basics",
  "Financial Statements",
  "Retirement",
  "Taxes"
];

export type LearnGuide = {
  slug: string;
  title: string;
  description: string;
};

export const LEARN_GUIDES: LearnGuide[] = [
  {
    slug: "investing-basics",
    title: "Beginner Investing",
    description: "The core ideas every new investor should understand before putting money to work."
  },
  {
    slug: "financial-statements",
    title: "Understanding Financial Statements",
    description: "How to read a balance sheet, income statement, and cash flow statement."
  },
  {
    slug: "taxes",
    title: "Investment Taxes",
    description: "Capital gains, dividends, tax-advantaged accounts, and other tax basics for investors."
  },
  {
    slug: "retirement",
    title: "Retirement Planning",
    description: "401(k)s, IRAs, employer matches, and the math behind a retirement plan."
  }
];
